services:
  - type: web
    name: keywordv2
    runtime: docker
    plan: free
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
